@LearnifyAPI_HostAddress = http://localhost:5132

GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets
Accept: application/json

###
GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Accept: application/json

###
POST {{LearnifyAPI_HostAddress}}/api/flashcard-sets
Content-Type: application/json

{
    "Title": "Algorithms 101",
    "Description": "Basic algorithms flashcard set"
}

###

PUT {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Content-Type: application/json 

{
    "Id": 1,
    "Title": "Updated Title",
    "Description": "Updated Description"
}

###
DELETE {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Accept: application/json

###