// Flashcard Sets Endpoints
@LearnifyAPI_HostAddress = http://localhost:5132

GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets
Accept: application/json

###
GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Accept: application/json

###
POST {{LearnifyAPI_HostAddress}}/api/flashcard-sets
Content-Type: application/json

{
    "Title": "Algorithms 101",
    "Description": "Basic algorithms flashcard set"
}

###

PUT {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Content-Type: application/json 

{
    "Id": 1,
    "Title": "Updated Title",
    "Description": "Updated Description"
}

###
DELETE {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1
Accept: application/json

###

// Flashcards Endpoints
GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1/flashcards
Accept: application/json

###
GET {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1/flashcards/1
Accept: application/json

### 
POST {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1/flashcards
Content-Type: application/json

{
    "Question": "What is a binary search?",
    "Answer": "A search algorithm that finds the position of a target value within a sorted array."
}

###
PUT {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1/flashcards/1
Content-Type: application/json

{
    "Id": 1,
    "Question": "Updated Question",
    "Answer": "Updated Answer"
}

###
DELETE {{LearnifyAPI_HostAddress}}/api/flashcard-sets/1/flashcards/1
Accept: application/json

###