# Required services for docker compose
services:
  backend:
    build: ./backend
    ports:
      - 5050:5000
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./learnify
    ports:
      - 3000:80
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:

